{{- $releaseName := .Release.Name -}}
{{- $chartName := include "polygon-parts-manager.name" . -}}
{{- $routeName := include "route.fullname" . }}
{{- $serviceName := include "service.fullname" . -}}
{{- $cloudProviderFlavor := include "polygon-parts-manager.cloudProviderFlavor" . -}}
{{- if and (and (.Values.enabled) (eq $cloudProviderFlavor "openshift")) (.Values.route.enabled) -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $routeName }}
  annotations:
    haproxy.router.openshift.io/rewrite-target: /
    {{- if .Values.route.timeout.enabled }}
    haproxy.router.openshift.io/timeout: {{ .Values.route.timeout.duration }}
    {{- end }}
spec:
  path: {{ .Values.route.path | default "/" }}
  to:
    kind: Service
    name: {{ $serviceName }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    {{- if .Values.route.tls.useCerts }}
    certificate: {{ .Values.route.tls.certificate | quote }}
    key: {{ .Values.route.tls.key | quote }}
    caCertificate: {{ .Values.route.tls.caCertificate | quote }}
    {{- end }}
{{- end -}}
