name: pull_request

on: [pull_request]

env:
  POSTGRES_PASSWORD: 'postgres'

jobs:
  pull_request:
    uses: MapColonies/shared-workflows/.github/workflows/pull_request.yaml@v2
    secrets: inherit
    with:
      usePostgres: true
      openApiFilePath: ./bundledApi.yaml
